# Generated by Django 4.1.7 on 2023-03-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_site'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site',
        ),
    ]
