# Generated by Django 4.1.7 on 2023-03-14 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_program'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Program',
        ),
    ]
